[build]
dockerfilePath = "packages/twenty-docker/twenty/Dockerfile"
dockerTarget = "twenty"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
